#! /bin/sh

sxhkd &
compton --config ~/.compton.conf --respect-prop-shadow &  
~/.config/polybar/launch.sh &
/usr/bin/dunst &
# change layout to the portuguese layout
setxkbmap -layout pt &

bspc monitor rdp0 -d 1 2 3 4 5 6 7 8 9 
bspc monitor rdp1 -d 10
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI1 -d 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
